#include <time.h>

void pausa(int numSegundos){

    int tempo = 1000 * numSegundos;
    clock_t inicio = clock();
    while (clock() < inicio + tempo);

}

void imprimeInstrucoes(){
    system("cls");
    printf(" -------------------------------------------------------\n");
    printf("| O objetivo principal do jogo e levar o personagem 'P' |\n");
    printf(" -------------------------------------------------------\n");
    printf("  |\n");
    printf("  v\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| P |   |   |   |   | X | X |   |    | P> |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| X | X | X |   |   |   | X |   |    Comandos:\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   | X |   |    1 - F, F, F\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   | X | X | X |   |   |   |    2 - F, F, D\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   |   |   |    3 - F, F, E\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    4 -\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    Vidas: 3\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   | O |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("Aperte enter para continuar.\n");
    fflush(stdin);
    getc(stdin);
    fflush(stdin);
    system("cls");

    
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| P |   |   |   |   | X | X |   |    | P> |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| X | X | X |   |   |   | X |   |    Comandos:\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   | X |   |    1 - F, F, F\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   | X | X | X |   |   |   |    2 - F, F, D\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   |   |   |    3 - F, F, E\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    4 -\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    Vidas: 3\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   | O |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("                              ^\n");
    printf("                              |\n");
    printf(" ------------------------------------------\n");
    printf("| Ao objetivo do outro lado do mapa, o 'O' |\n");
    printf(" ------------------------------------------\n");
    printf("Aperte enter para continuar.\n");
    fflush(stdin);
    getc(stdin);
    fflush(stdin);
    system("cls");

    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| P |   |   |   |   | X | X |   |    | P> |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| X | X | X |   |   |   | X |   |    Comandos:\n");
    printf("|---|---|---|---|---|---|---|---|                   -------------------------------\n");
    printf("|   |   |   |   |   |   | X |   |    1 - F, F, F   | Essas sao as instrucoes       |\n");
    printf("|---|---|---|---|---|---|---|---|                  | que voce podera utilizar      |\n");
    printf("|   |   | X | X | X |   |   |   |    2 - F, F, D   | durante a execucao do jogo,   |\n");
    printf("|---|---|---|---|---|---|---|---|                  | porem elas mudam em cada fase |\n");
    printf("|   |   |   |   |   |   |   |   |    3 - F, F, E   | entao tome cuidado!           |\n");
    printf("|---|---|---|---|---|---|---|---|                   -------------------------------\n");
    printf("|   |   |   |   |   | X |   |   |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    Vidas: 3\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   | O |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("Aperte enter para continuar.\n");
    fflush(stdin);
    getc(stdin);
    fflush(stdin);
    system("cls");

    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| P |   |   |   |   | X | X |   |    | P> |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| X | X | X |   |   |   | X |   |    Comandos:\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   | X |   |    1 - F, F, F\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   | X | X | X |   |   |   |    2 - F, F, D\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   |   |   |    3 - F, F, E\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    4 -\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    Vidas: 3\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   | O |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("Informe suas jogadas para a fase 1, para finalizar insira -1 no comando a ser utilizado.\n");
    printf(" Qual o comando ira utilizar?\n");
    printf("1\n");
    printf(" ---------------------------------------------\n");
    printf("| Voce devera colocar uma jogada de cada vez, |\n");
    printf("| comecando com o comando a ser executado     |\n");
    printf(" ---------------------------------------------\n");
    printf("Aperte enter para continuar.\n");
    fflush(stdin);
    getc(stdin);
    fflush(stdin);
    system("cls");

    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| P |   |   |   |   | X | X |   |    | P> |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| X | X | X |   |   |   | X |   |    Comandos:\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   | X |   |    1 - F, F, F\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   | X | X | X |   |   |   |    2 - F, F, D\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   |   |   |    3 - F, F, E\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    4 -\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    Vidas: 3\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   | O |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("Informe suas jogadas para a fase 1, para finalizar insira -1 no comando a ser utilizado.\n");
    printf("Quantas vezes ira utilizar o 1o comando?\n");
    printf("1\n");
    printf(" ------------------------------------------------------\n");
    printf("| Em seguida quantas vezes esse comando sera executado |\n");
    printf(" ------------------------------------------------------\n");
    printf("Aperte enter para continuar.\n");
    fflush(stdin);
    getc(stdin);
    fflush(stdin);
    system("cls");

    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| P |   |   |   |   | X | X |   |    | P> |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| X | X | X |   |   |   | X |   |    Comandos:\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   | X |   |    1 - F, F, F\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   | X | X | X |   |   |   |    2 - F, F, D\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   |   |   |    3 - F, F, E\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    4 -\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    Vidas: 3\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   | O |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("Informe suas jogadas para a fase 1, para finalizar insira -1 no comando a ser utilizado.\n");
    printf(" Qual o comando ira utilizar?\n");
    printf("-1\n");
    printf(" ------------------------------------------------------\n");
    printf("| Para finalizar a sequencia de jogadas e testar se sua |\n");
    printf("| fila de comandos esta correta, passe -1 no comando e  |\n");
    printf("| entao o jogo ira comecar a testar sua jogada.         |\n");
    printf(" ------------------------------------------------------\n");
    printf("Aperte enter para continuar.\n");
    fflush(stdin);
    getc(stdin);
    fflush(stdin);
    system("cls");

    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| P |   |   |   |   | X | X |   |    | P> |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| X | X | X |   |   |   | X |   |    Comandos:\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   | X |   |    1 - F, F, F\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   | X | X | X |   |   |   |    2 - F, F, D\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   |   |   |    3 - F, F, E\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    4 -\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    Vidas: 3\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   | O |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    pausa(1);
    system("cls");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   | P |   |   |   | X | X |   |    | P> |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| X | X | X |   |   |   | X |   |    Comandos:\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   | X |   |    1 - F, F, F\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   | X | X | X |   |   |   |    2 - F, F, D\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   |   |   |    3 - F, F, E\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    4 -\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    Vidas: 3\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   | O |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    pausa(1);
    system("cls");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   | P |   |   | X | X |   |    | P> |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| X | X | X |   |   |   | X |   |    Comandos:\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   | X |   |    1 - F, F, F\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   | X | X | X |   |   |   |    2 - F, F, D\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   |   |   |    3 - F, F, E\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    4 -\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    Vidas: 3\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   | O |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    pausa(1);
    system("cls");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   | P |   | X | X |   |    | P> |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| X | X | X |   |   |   | X |   |    Comandos:\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   | X |   |    1 - F, F, F\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   | X | X | X |   |   |   |    2 - F, F, D\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   |   |   |    3 - F, F, E\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    4 -\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    Vidas: 3\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   | O |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    pausa(1);
    system("cls"); 
    printf(" -------------------------------------------------\n");
    printf("|        __      ______   _____ ______            |\n");
    printf("|        \\ \\    / / __ \\ / ____|  ____|           |\n");
    printf("|         \\ \\  / / |  | | |    | |__              |\n");
    printf("|          \\ \\/ /| |  | | |    |  __|             |\n");
    printf("|           \\  / | |__| | |____| |____            |\n");
    printf("|     ______ \\/___\\____/_\\_____|______|_   _      |\n");
    printf("|    |  ____|  __ \\|  __ \\ / __ \\| |  | | | |     |\n");
    printf("|    | |__  | |__) | |__) | |  | | |  | | | |     |\n");
    printf("|    |  __| |  _  /|  _  /| |  | | |  | | | |     |\n");
    printf("|    | |____| | \\ \\| | \\ \\| |__| | |__| | |_|     |\n");
    printf("|    |______|_|  \\_\\_|  \\_\\\\____/ \\____/  (_)     |\n");        
    printf(" -------------------------------------------------\n");
    pausa(1);
    system("cls");           
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| P |   |   |   |   | X | X |   |    | P> |\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("| X | X | X |   |   |   | X |   |    Comandos:\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   | X |   |    1 - F, F, F\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   | X | X | X |   |   |   |    2 - F, F, D\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   |   |   |   |    3 - F, F, E\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    4 -\n");
    printf("|---|---|---|---|---|---|---|---|\n");
    printf("|   |   |   |   |   | X |   |   |    Vidas: 2\n");
    printf("|---|---|---|---|---|---|---|---|           ^\n");
    printf("|   |   |   |   |   | X |   | O |           |\n");
    printf("|---|---|---|---|---|---|---|---|           |\n");
    pausa(1);
    printf(" ------------------------------------------------------\n");
    printf("| Como o objetivo nao foi cumprido, o jogador perdera  |\n");
    printf("| uma vida, restando apenas 2. Caso as vidas fiquem    |\n");
    printf("| zeradas, o jogo voltara ao menu iniciar. Porem se    |\n");
    printf("| fizer a sequencia correta, passara a fase, indo para |\n");
    printf("| a sequencia em Pilha e na ultima, devera buscar o    |\n");
    printf("| objetivo: sua primeira parte em fila e segunda em    |\n");
    printf("| pilha                                                |\n");
    printf(" ------------------------------------------------------\n");
    printf("Aperte enter para voltar ao menu inicial.\n");
    fflush(stdin);
    getc(stdin);
    fflush(stdin);
    system("cls");

}

